const LOGGED_IN_USER = "LOGGED_IN_USER";
const LOGOUT = "LOGOUT";
const SEARCH_QUERY = "SEARCH_QUERY";
const ADD_TO_CART = "ADD_TO_CART";
const SET_VISIBLE = "SET_VISIBLE";

export const actionTypes = {
  LOGGED_IN_USER,
  LOGOUT,
  SEARCH_QUERY,
  ADD_TO_CART,
  SET_VISIBLE,
};
